### ISSUE TITLE
Turkey Markets not showing

### ISSUE THREAD

**Issue by xanadunf** [xanadunf/matchbook#2]
Issue created by user: '1twa'.

For example I can not see the games for Soccer, Turkey - Super Lig that
take place tomorrow (2/4/16).
E.g Eskisehirspor vs. Galatasaray

**Comment by xanadunf** [comment]
Solution: try modifying the start_date and end_date parameters. See for example: 

event_data <- mb_get_events(session_data=session_details,sport_ids=football_sport_id,start_date="2016-04-02 00:00:00",end_date="2016-04-03 00:00:00")
event_data[grep(tolower("Konyaspor"), tolower(event_data$name)),]
event_data[unlist(lapply(event_data$`meta-tags`,function(x) ifelse(sum(x$name=="Turkey")>0,TRUE,FALSE))),]

**Comment by xanadunf** [comment]
backticks around meta-tags in the above snippet have been interpreted by markdown see here also:

event_data[unlist(lapply(event_data$`meta-tags`,function(x) ifelse(sum(x$name=="Turkey")>0,TRUE,FALSE))),];

**Comment by 1twa** [comment]
Thank for your reply. 
The problem was that I filtered the data by a category-id, which I assumed corresponds to a specific league ID. However, it seems that this ID is not specific for a league.
