### ISSUE TITLE
SportsID = 7 (horse racing)

### ISSUE THREAD

**Issue by 1twa** [xanadunf/matchbook#3]
I don't get events when using SportsID = 7 (horse racing).
Is there anything special to this sportsid?

**Comment by samiresquire** [comment]
The same goes for tennis. I believe you need to use the new EDGE endpoint instead.

Will this package be updated for the new system they are using?

**Comment by xanadunf** [comment]
this has been resolved. All sports should now be visible, inclusive of Horse Racing
