### ISSUE TITLE
New end point system

### ISSUE THREAD

**Issue by samiresquire** [xanadunf/matchbook#4]
Hi I was wondering if the package will be updated for the new edge end point system they are using for a few sports currently will be migrating over the remaining sports in the coming months?

Many thanks

**Comment by xanadunf** [comment]
yes it will - I will update it in the next few days as soon as I get hold of the new endpoints.

**Comment by samiresquire** [comment]
Hi do let me know if you need any information on this as I have details on the new  endpoints.

**Comment by xanadunf** [comment]
this has now been completed
